name: Build Docker images

on:
  push:

env:
  PHPSTAN_VERSION: 0.12.32
  DOCKER_REPOSITORY: aragon999/phpstan-shopware

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        shopware-version: ['v6.2.0', 'v6.2.1', 'v6.2.2']

    runs-on: ubuntu-18.04
    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Build docker image
        uses: docker/build-push-action@v1
        with:
          repository: ${{ env.DOCKER_REPOSITORY }}
          build_args: PHPSTAN_VERSION=${{ env.PHPSTAN_VERSION }},SHOPWARE_VERSION=${{ matrix.shopware-version }}
          tags: ${{ matrix.shopware-version }},${{ matrix.shopware-version }}-${{ env.PHPSTAN_VERSION }}
          push: false

      - name: Run basic checks
        run: |
          docker run --rm ${DOCKER_REPOSITORY}:${{ matrix.shopware-version }}-${PHPSTAN_VERSION} \
            analyze --level 5 \
            /composer/vendor/shopware/core/Content/Property \
            /composer/vendor/shopware/core/Checkout/Cart
